# Generated by Django 4.2.6 on 2023-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('teacher_name', models.CharField(max_length=200)),
                ('name_of_school', models.TextField()),
                ('activity_covered', models.CharField(max_length=200)),
                ('total_students', models.PositiveIntegerField()),
                ('total_female_students', models.PositiveIntegerField()),
                ('total_groups_formed', models.PositiveIntegerField()),
                ('total_groups_completed_activity', models.PositiveIntegerField()),
                ('do_students_form_groups', models.BooleanField()),
                ('do_students_ask_questions', models.CharField(max_length=200)),
                ('initiative_taken_by', models.CharField(max_length=200)),
                ('student_sentiment_after_class', models.CharField(max_length=400)),
                ('other_feedback', models.TextField()),
                ('name_of_block', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('disctrict', models.CharField(max_length=100)),
            ],
        ),
    ]
